version: "3"

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:latest
    restart: unless-stopped
    container_name: booking_mysql
    tty: true
    ports:
      - "4506:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: booking
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  php:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes: 
      - ./src:/var/www/html
    ports:
      - "9100:9000"
    networks:
      - laravel
  
  npm:
    image: node:alpine3.15
    container_name: npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: [npm]

  artisan:
    build:
      context: .
    container_name: artisan
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']